### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by duhaime**
@spaceraccoon I think we should move to yarn.lock rather than the npm shrinkwrap. Also wanted to reflect the doco change and quash a warning in the current master that springs when attempting to connect with Mongo. If this looks good feel free to merge and drop the shrinkwrap...

### CODE REVIEW

**Comment by spaceraccoon** [comment]
Great, thanks! Yes, I also prefer to use yarn.

**Comment by spaceraccoon** [comment]
As a side note, I noticed some deprecation warnings - do we plan to upgrade to React 16 and a couple of the other dependencies?

**Comment by duhaime** [comment]
It would be awesome to move to 16. Would you have time for that? If not just let me know and we can find a solution...

**Comment by duhaime** [comment]
ping @spaceraccoon

**Comment by spaceraccoon** [comment]
Sure! I'm almost done with the urgent feature requests for this week and will look into it. @duhaime I know for the `Confirm` modal fragments would've been super useful.

**Comment by duhaime** [comment]
@spaceraccoon Yes I hear you. Fire at will when time permits...

**Pull request merged**
